# Generated by Django 4.1.7 on 2023-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sutudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('grade', models.PositiveSmallIntegerField()),
                ('school', models.CharField(max_length=200)),
            ],
        ),
    ]
