# Generated by Django 4.1.7 on 2023-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutudent',
            name='user_name',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
